### ISSUE TITLE
[Improvement] Possible threading issue in `ClientPoolImpl.java`

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#1878]
### What would you like to be improved?

notify()and notifyAll() both wake up sleeping threads, but notify() only wakes up one single thread, while notifyAll() wakes them all up. Perhaps notifyAll() should be used inside release() instead of notify()?

### How should we improve?

Investigate and change if needed.

**Comment by noidname01** [comment]
Hi, I investigated this problem. 

`notify()` and `notifyAll()` work almost the same in this scenario. Because even if `notifyAll()` wake up all the sleeping threads, only one of them get `this` to get into `synchronized(this)`, the rest of them might halt while trying to acquire `this` or even get the `signal` and fall into sleep again. So there is no big difference between these two methods.

**Comment by LiuQhahah** [comment]
Hi @justinmclean 
The issue had been solved on https://github.com/apache/gravitino/issues/4183 
Please close the issue.
Thanks.
