### ISSUE TITLE
[Improvement] CatalogConnectorManager.java has no unit test / coverage

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#2181]
### What would you like to be improved?

CatalogConnectorManager.java has no unit test / coverage

### How should we improve?

Write unit tests to provide coverage of code.

**Comment by silenceland** [comment]
Hello, I'm a fresh hand to this project and I'm very interested in it. I would like to try out this issue. Please assign it to me. Thank you!

**Comment by shaofengshi** [comment]
@silenceland you can go ahead with a comment like "I'm working on this". Later when the PR be raised and merged, we will update the assignee. Thank you!

**Comment by orenccl** [comment]
Hello, I noticed that this issue has been pending for some time, and the previous contributor hasn't provided updates. I would like to take over this issue and start working on it. Please let me know if I can proceed. Thank you!

**Comment by justinmclean** [comment]
@orenccl, thanks for your offer to help. I've assigned the issue to you.

**Comment by orenccl** [comment]
Hi @justinmclean,

I've checked the project and found that tests are already implemented for this component. Would it be possible to close this issue?

Although the test coverage could potentially be optimized, this part is a bit challenging for me since unit testing in this area is complex, and I'm not fully familiar with the entire project yet. I'd like to focus on other beginner-friendly issues first.

![image](https://github.com/user-attachments/assets/9b0b5037-8e27-4b32-95a4-9e17a4e4bfb1)

**Comment by justinmclean** [comment]
Thanks for looking into this, as we do now have good coverage I
m closing this issue.
