### ISSUE TITLE
[Improvement] Possible incorrect initialisation in AuthenticationConfig.java

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#4184]
### What would you like to be improved?

This line:
```
 .createWithDefault(KerberosConfig.DEFAULT_IMPERSONATION_ENABLE);
```
and this line:
```
 KerberosConfig.DEFAULT_IMPERSONATION_ENABLE,
```

Referencing a member of a subclass during initialisation, may give unexpected results because the child class might not have been initialised yet.

**Comment by ashwin1596** [comment]
Hi,

I'm interested in working on this issue. Could you please provide more details?

Thank you!

**Comment by justinmclean** [comment]
KerberosConfig extends AuthenticationConfig and AuthenticationConfig uses KerberosConfig.DEFAULT_IMPERSONATION_ENABLE which could lead to some issues. One way of fixing it, off teh top of my head, would be to move DEFAULT_IMPERSONATION_ENABLE to AuthenticationConfig, but I'm not sure if that's the only way or best way.

**Comment by ashwin1596** [comment]
Since DEFAULT_IMPERSONATION_ENABLE is a static final (constant) member, it does not depend on any instance and is initialized when the class is loaded. Therefore, it should not create any issue even if the subclass has not been initialized.

To improve code clarity and organization, I have moved DEFAULT_IMPERSONATION_ENABLE from KerberosConfig to AuthenticationConfig. This change ensures that the constant is placed in a more appropriate context, reflecting its role and usage more accurately.

Let me know if you have any suggestions.
