### ISSUE TITLE
[Improvement] Possible bug in HiveTable.java

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#4188]
### What would you like to be improved?

buildStorageDescriptor has a local variable `sd` that hides a field also called `sd`

### How should we improve?

Should this method be using the field?

**Comment by ashwin1596** [comment]
I can take this up!

**Comment by ashwin1596** [comment]
I have reviewed the code, and since buildStorageDescriptor creates a new storage descriptor based on specific input parameters, it is correct to create a local instance of StorageDescriptor.

To avoid confusion with the class member sd, a possible fix is to rename the local StorageDescriptor instance.

If that's acceptable, I can make that update.

**Comment by justinmclean** [comment]
Renaming to the variable to make the intent clearer would be best thanks, so please go ahead with that update.
