### ISSUE TITLE
[Improvement] replace switch with if statement

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#4409]
### What would you like to be improved?

The switch in JDBCBackend.java (line 371) can be replaced by an if statement.

### How should we improve?

As above, it is more readable.

**Comment by mushroom528** [comment]
Can I work on this issue?

**Comment by justinmclean** [comment]
Sure you can!

**Comment by jerryshao** [comment]
Let me clarify more on this. I think we deliberately chose switch..case instead of if..else here, because we will add more relation types here later on. Also, I don't see any readable problem here using switch..case, so I'm inclined not doing such refactoring unless we really find issues here.

If you have different opinions on this, you can leave messages here, otherwise I will close this issue to avoid misleading to many new contributors.
