### ISSUE TITLE
[Improvement] Add the document about access control

### ISSUE THREAD

**Issue by jerqi** [apache/gravitino#4467]
### What would you like to be improved?

Refactor the document about `docs/security.md`. 

Add the document about access control

### How should we improve?

Refactor the document about security. Split the document about security into 3 parts. Authentication, HTTPS and access control.

Add the document about access control.

**Comment by Dipti0704** [comment]
i would like to work on this issue kindly assign me

**Comment by jerryshao** [comment]
What do you actually want to do in this issue @jerqi , the description is too simple, others even don't know what do you actually want to fix, please refactor this issue to add more words.

 @Dipti0704 thanks for your interest and PR, if this issue is not related to your change, can you please create another issue to track your work?
