### ISSUE TITLE
[Bug report] UI: Some password field is still plaintext

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4506]
### Version

main branch

### Describe what's wrong

<img width="1219" alt="image" src="https://github.com/user-attachments/assets/710caebf-09a7-48a2-bc88-b4557ce7e1b0">
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/55c74b73-e151-4c90-92a3-56625711e418">

### Error message and/or stacktrace

N/A

### How to reproduce

1. Create a catalog with password field
2. See the password on details pages

**Comment by LauraXia123** [comment]
@featherchen hi, can you help fix this issue?

**Comment by featherchen** [comment]
@LauraXia123 Okey, I'll take a look at it.

**Comment by featherchen** [comment]
@LauraXia123  @danhuawang This is a related but different issue with #4384, the latter deals with password input, and the former wants to hide password display in detail.

Just hiding the password is trivial, but I think the real problem is if we hide it in display, where can the user see their jdbc-password.

**Comment by LauraXia123** [comment]
@featherchen In the future, we will open up viewing access to those who have it. Hide it for now.

**Comment by featherchen** [comment]
@LauraXia123 I have hide it in frontend via #4561, however the password is still plaintext in the http response from backend
![Screenshot from 2024-08-16 15-34-29](https://github.com/user-attachments/assets/a225d7c6-ce95-4c58-bb60-a274efd52dd5)
I think this issue is related to the backend api design, and maybe need to open a new issue to discuss it ?

**Comment by LauraXia123** [comment]
yeah, we can create new issue to follow it.
