### ISSUE TITLE
[Bug report] Dropping a fileset schema as a cascade misses dropping child filesets

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#4842]
### Version

main branch

### Describe what's wrong

In current `dropSchema` codes,  when we drop a fileset schema with cascade, it only judges the schemaPath's subfile but missing the child fileset:
https://github.com/apache/gravitino/blob/3dd59a8c59ede2774123fe96eb989adec13c3da3/catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java#L509-L517

### Error message and/or stacktrace

don't throw an error

### How to reproduce

  - create a fileset schema `s1` with location `/a`
  - create a fileset `s1.f1` under above schema with location `/b`
  - drop the schema `s1` with cascade
  - the `/a` was removed but `/b` still exists (that's the problem)

**Comment by mchades** [comment]
The current fileset schema cascade deletion only applies to the location of the schema. 

I am not sure if we need to consider the sub-files under the location of the schema during cascade deletion, or just need to consider the child-filesets' locations of the schema? Or do we need to consider both? 

Do you have any suggestions? @jerryshao @xloya @coolderli

**Comment by xloya** [comment]
From the current scenario within Xiaomi, we will not directly Drop the schema, but only support Drop the fileset. If we need to support Drop Schema, it seems reasonable to delete the storage path of Managed Fileset under the schema at the same time, but the cost may be slightly higher because recursive deletion is required. Maybe disable that deleting schema of fileset recursively is also an option.

**Comment by mchades** [comment]
@jerryshao WDYT?

**Comment by jerryshao** [comment]
Yes, it is reasonable to delete the storage location related to schema. but as @xloya mentioned, the cost is quite high, especially for object store. Maybe we can do a async deletion for data if the schema is marked as deleted.
