### ISSUE TITLE
[Improvement] Group supports list operations

### ISSUE THREAD

**Issue by jerqi** [apache/gravitino#4873]
### What would you like to be improved?

We need to know all the group informations. We don't support to list groups operation.

### How should we improve?

We need to know all the group informations. We don't support to list groups operation.

**Comment by LiuQhahah** [comment]
Hi @jerqi 

From the code (https://github.com/apache/gravitino/blob/c7200c89a04ed8dab6f3bfe4d2f209220dd5415d/server/src/main/java/org/apache/gravitino/server/web/rest/GroupOperations.java#L49), we can find that the level is metalake, so I want to know whether the  all of " all the group information"  means the metalake level instead of the root level?
