### ISSUE TITLE
[EPIC] Add CLI interface for Gravitino

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#4943]
### Describe the proposal

Currently, Gravitino provides web UI, Java SDK, Python SDK to manipulate the metadata. The current web UI is not a full functionality UI, user still needs to write Java, Python codes or directly use REST APIs to communicate with Gravitino, which makes user hard to use Gravitino at the first stage.

Instead of adding more and more features in web UI, we think that adding a simple CLI interface will significantly help the users, especially the developers. So in this EPIC issue, we are planning to the CLI support for Gravitino.

### Task list

- [x] #5057
- [x] #5059
- [x] #5061
- [x] #5131
- [x] #5162
- [x] #5281
- [x] #5294
- [x] #5379
- [x] #5383
- [x] #5384
- [x] #5560

**Comment by jerryshao** [comment]
@justinmclean , can you please post the design doc here, so we can we have a discussion on the issue.

**Comment by justinmclean** [comment]
## Background

Other catalogs provide a CLI to interact with the catalog’s metadata. A Gravitino API would also be useful to be able to script Gravitino, automate Gravitino setup, put metadata under version control, for demos or a variety of other uses.

## Goals
- A simple wrapper around the Gravitino REST service
- Provide help on CLI use to user
- Supports listing of simple information  about  metalakes, catalogs, schema and tables
- Can show simple text output or raw JSON text from REST call as an option
- Create and delete metalakes, catalogs and schema
- To be a useful simple utility
- Simple user input validation
- Simple error handling
- Debug/log option

## Not Goals
- Not to implement the full REST API
- Not to display all information about a know entity
- Initial versions assumes no authentication

## Design
The CLI would be implemented in Python using requests library for the REST interface and click for the CLI. The command consists of options to specify the metalake, catalog, schema etc etc, a way to specify the format and a command to perform an action.

## Suggested Usage:

```
Usage: GravCLI.py [OPTIONS] [COMMAND]
Options:
  --host TEXT      Gravitino REST host and port (host:port)
  --metalake TEXT  Metalake name
  --catalog TEXT   Catalog name
  --schema TEXT    Schema name
  --table TEXT     Table name
  --format TEXT    "simple" or “JSON"
  --help           Show this message and exit.
```

Optionally consider having the commands as options i.e add –list –details –delete –create instead of using a command.

## Commands
- Details (default) displays details about the specified entity.
- List displays details about the children of a specified entity. e.g. list all often tables in a catalog.
- Delete deletes an entity.
- Create creates an entity. Extra options than those listed above will be needed for this based on each entity.

**Example Usage**
List info about a metalake:
`python3 GravCLI.py --metalake metalake_demo`

List info about tables:
`python3 GravCLI.py --metalake metalake_demo --catalog catalog_mysql --schema demo_llamaindex --table city_stats list`

List info about a metalake’s catalogs:
`python3 GravCLI.py --metalake metalake_demo list`

Create info a new metalake:
`python3 GravCLI.py --metalake metalake_new –comment “a new metalake”  create`

Delete a metalake:
`python3 GravCLI.py --metalake metalake_demo delete`

Note command can come first and doesn’t have to be at the end.

**Comment by jerryshao** [comment]
I think it is simple to use the current Java Gravitino to create a CLI tool. Current Python client only supports Fileset, if you want to use Python, then you have to write all the rest protocols from ground.

Also, for the CLI arguments, can you please investigate some other similar projects to see how they design and how we can refer?

Besides, I think the design doc should list all the commands about list, create, get, alter, and delete for all the entities, also should include access control operations and tag operations, to achieve them in CLI also.

**Comment by jerryshao** [comment]
Also please put the design doc in the gdoc, so we can comment inline.

**Comment by justinmclean** [comment]
The above isn't using the Python client. It's using the REST interface - this is what most other catalogs do.

**Comment by jerryshao** [comment]
Then you have to implement all the REST interfaces including metalake, catalog, schema, table..., also including authorization, this is a huge work, why can't we use the existing Java client and do a simple wrapper to achieve the CLI?

**Comment by justinmclean** [comment]
The entire basic REST interface in Python is about 100 lines of code, much less than the equilivant Java code.

**Comment by jerryshao** [comment]
I don't think so, once you implement some complicated "create" or "alter" command, you will have to handle complicated cases including serialization and deserialization. Also, in Java client we already achieve some authorization methods like Kerberos, oauth, etc. If you want to write them in plain using Python, you will have to deal with them. It's not as simple as you think.

**Comment by justinmclean** [comment]
I have also looked at several other CLIs and the design above is similar to how they do it. My initial thought was not to implement the entire API/REST interface, but it can be extended once we we have something that useful.

**Comment by jerryshao** [comment]
If you're not doing a complete CLI, then there's no difference compared to the current web UI, users still cannot fully experience the whole features easily.

**Comment by justinmclean** [comment]
The initial objective (as described above) is not to implement the full API, but we can expand on the initial API to eventually cover everything. If you want me to break it up into stages and put what is developed in each, I can do that.

**Comment by jerryshao** [comment]
My feeling is that if we use Java client for CLI, then we already handle most of the of the JSON serde and security things, so we can only focus on CLI implementation. But if we choose to use Python, we will need to implement from the ground, this may take lots of work, especially since we have several data structures like "type", and "expression", they're nested and complicated to serialize/deserialize. If we choose Java, the current Java client already did it for us, so we don't have to do it again. The key thing is that for CLI, we don't have to do the JSON/REST thing again, we can leverage the current client and focus on the CLI thing only. It's not a problem of choosing languages, it's a problem of not doing duplicated work. If there's a full-functionality Python client, then I'm also fine with a simple wrapper of that Python client to achieve CLI in Python.
It's just my comment, I think we should discuss this in the community and involve others' opinions, I will also post this on the issue.

**Comment by jerryshao** [comment]
> The initial objective (as described above) is not to implement the full API, but we can expand on the initial API to eventually cover everything. If you want me to break it up into stages and put what is developed in each, I can do that.

This is a huge issue, it should be broken into multiple small tasks to achieve them step by step.

**Comment by mchades** [comment]
> Link to design doc: https://docs.google.com/document/d/19CXHeg_5iphO8D3UD16rexVE23M4TMZXOU3X0lBqL6A/edit?usp=sharing

IMO, the current design doesn't seem to be very different from using `curl` directly.

As a CLI, I think it's more about user interaction, and results presentation, but the current CLI seems to be more of a simplification of the use of the `curl` tool, and doesn't bring a lot of convenience to the user. 

Feel free to point out if I've misunderstood anything!

**Comment by justinmclean** [comment]
It is easier to use than`curl` as the user doesn't need to supply correctly format JSON, it fills in many of the default parameters, and its output is more user-friendly.

**Comment by justinmclean** [comment]
Everything has been done and merged
